#!/bin/sh
# Diode Server
# Copyright 2019 IoT Blockchain Technology Corporation LLC (IBTC)
# Licensed under the Diode License, Version 1.0
export ERL_EPMD_ADDRESS=127.0.0.1
export MIX_ENV=prod
exec iex --sname remsh_$$ --remsh diode
