#!/bin/sh
# Diode Server
# Copyright 2019 IoT Blockchain Technology Corporation LLC (IBTC)
# Licensed under the Diode License, Version 1.0
rm -rf data/ state/
export MIX_ENV=dev
mix deps.get
exec iex -S mix run 
