#!/bin/sh
# Diode Server
# Copyright 2019 IoT Blockchain Technology Corporation LLC (IBTC)
# Licensed under the Diode License, Version 1.0
rm -rf data_test/
export MIX_ENV=test
mix deps.get
exec iex -S mix run 
