#!/bin/bash
# Diode Server
# Copyright 2019 IoT Blockchain Technology Corporation LLC (IBTC)
# Licensed under the Diode License, Version 1.0
n=$1
if [[ "$n" == "" ]]; then
  n=0
fi


ulimit -n 120000
export ERL_CRASH_DUMP_BYTES=5000000000
export ERL_EPMD_ADDRESS=127.0.0.1
export MIX_ENV=prod
export DATA_DIR=staging_data${n}/
export CHAINDEF=stagenet
export PEER_PORT=190${n}0
export EDGE2_PORT=190${n}1
export SEED=diode://localhost:19000
mix deps.get
export ELIXIR_ERL_OPTIONS="+sbwt none -noinput -noshell -sname staging${n} +Mea min"
exec elixir -S mix run --no-halt
