#!/bin/bash
set -e

case "$1" in
    "remsh")
        export ELIXIR_ERL_OPTIONS="-setcookie $COOKIE"
        exec iex --sname remsh_$$ --remsh diode
        ;;
    "")
        export ELIXIR_ERL_OPTIONS="+sbwt none -noinput -noshell -sname diode +A 8"
        exec iex -S mix run --no-halt
        ;;
    *)
        echo "Usage: $0 <''|remsh>"
        exit 1
        ;;
esac