#!/bin/bash
# Diode Server
# Copyright 2021-2024 Diode
# Licensed under the Diode License, Version 1.1
if [[ $1 == "" ]]; then
  echo "Need a host parameter"
  echo "You can try localhost:8545"
  exit
fi

if [[ $2 == "" ]]; then
  echo "Need a sample file parameter"
  echo "You can try getObject.json"
  exit
fi

curl -k -H "Content-Type: application/json" -X POST -o out.json --data @$2 $1 
